// Datos iniciales de ejemplo. El panel de administración sobrescribe
// estos valores una vez que el local carga su propia carta.

export const defaultMenu = {
  settings: {
    brandName: 'Café C',
    logoLetter: 'C',
    logoImage: null, // dataURL opcional subida desde el admin
    accentColor: '#D9A441',
    bgColor: '#1B140F',
    surfaceColor: '#241B14',
    textColor: '#F6EFE4',
    mutedColor: '#A8998A',
    fontHeading: 'Sora',
    fontBody: 'Work Sans',
    currency: '$',
    welcomeTitle: '¿Qué vas a elegir?',
  },
  categories: [
    {
      id: 'desayuno-merienda',
      label: 'Desayuno | Merienda',
      featured: true,
      subcategories: [
        { id: 'bebidas-dm', label: 'Bebidas', featured: true },
        { id: 'dulce-dm', label: 'Dulce', featured: false },
        { id: 'salado-dm', label: 'Salado', featured: false },
      ],
    },
    {
      id: 'almuerzo-cena',
      label: 'Almuerzo | Cena',
      featured: true,
      subcategories: [
        { id: 'entradas-ac', label: 'Entradas', featured: true },
        { id: 'principales-ac', label: 'Principales', featured: false },
        { id: 'postres-ac', label: 'Postres', featured: false },
      ],
    },
    {
      id: 'cositas-ricas',
      label: 'Cositas Ricas',
      featured: false,
      subcategories: [],
    },
    {
      id: 'novedades',
      label: 'Novedades',
      featured: false,
      subcategories: [],
    },
  ],
  products: [
    {
      id: 'p-americano',
      categoryId: 'desayuno-merienda',
      subcategoryId: 'bebidas-dm',
      name: 'Cafe Americano',
      description: 'Café negro de grano tostado',
      price: 2500,
      image: null,
      icon: 'coffee',
    },
    {
      id: 'p-flatwhite',
      categoryId: 'desayuno-merienda',
      subcategoryId: 'bebidas-dm',
      name: 'Flat White',
      description: 'Espresso doble con leche vaporizada suave',
      price: 2500,
      image: null,
      icon: 'coffee',
    },
    {
      id: 'p-capuccino',
      categoryId: 'desayuno-merienda',
      subcategoryId: 'bebidas-dm',
      name: 'Capuccino',
      description: 'Espresso, leche vaporizada y espuma cremosa',
      price: 2500,
      image: null,
      icon: 'coffee',
    },
    {
      id: 'p-mocaccino',
      categoryId: 'desayuno-merienda',
      subcategoryId: 'bebidas-dm',
      name: 'Mocaccino',
      description: 'Capuccino con toque de chocolate',
      price: 2500,
      image: null,
      icon: 'coffee',
    },
    {
      id: 'p-exprimido',
      categoryId: 'desayuno-merienda',
      subcategoryId: 'bebidas-dm',
      name: 'Exprimido de Naranja',
      description: 'Jugo de naranja exprimido en el momento',
      price: 2500,
      image: null,
      icon: 'juice',
    },
    {
      id: 'p-limonada',
      categoryId: 'desayuno-merienda',
      subcategoryId: 'bebidas-dm',
      name: 'Limonada de maracuyá',
      description: 'Limonada fresca con maracuyá',
      price: 2500,
      image: null,
      icon: 'juice',
    },
    {
      id: 'p-medialunas',
      categoryId: 'desayuno-merienda',
      subcategoryId: 'dulce-dm',
      name: 'Medialunas (x2)',
      description: 'Medialunas de manteca recién horneadas',
      price: 2200,
      image: null,
      icon: 'pastry',
    },
    {
      id: 'p-tostado',
      categoryId: 'desayuno-merienda',
      subcategoryId: 'salado-dm',
      name: 'Tostado jamón y queso',
      description: 'Pan de miga tostado con jamón y queso',
      price: 3200,
      image: null,
      icon: 'sandwich',
    },
  ],
};
